[licenses]
unlicensed = "deny"
allow = ["MIT", "Apache-2.0", "BSD-2-Clause", "CC0-1.0", "ISC", "MPL-2.0"]
copyleft = "warn"
default = "deny"

[[licenses.exceptions]]
allow = ["Unicode-DFS-2016"]
name = "unicode-ident"
version = "1.0.3"

[bans]
multiple-versions = "deny"
skip-tree = [
    { name = "windows-sys" },
    { name = "itertools" },
    { name = "bitflags" },
]
